language: node_js
os: ['osx', 'linux', 'windows']
node_js: ['node']
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH="$HOME/.yarn/bin:$PATH"
  - apt-get install fakeroot
cache: yarn
script: electron-forge publish